apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  env: "port"
  db-URL: "192.15.16.0"

---

apiVersion: v1
kind: Pod
metadata:
  name: ip-app
spec:
  containers:
  - name: ip-app
    image: harshajain/ip-app:latest
    ports:
    - containerPort: 8080
    env:
    - name: ENVIRONMENT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: env
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: db-URL
