apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-hpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-php
  template:
    metadata:
      labels:
        app: app-php
    spec:
      containers:
        - name: hpv-c
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: my-ser
spec:
  type: ClusterIP
  selector:
    app: app-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
