apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp-sec
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ngx1
  template:
    metadata:
      labels:
        app: ngx1
    spec:
      containers:
        - name: my-pod
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: HV
              valueFrom:
                secretKeyRef:  
                  name: my-secret
                  key: db_pass
