apiVersion: v1 
kind: Pod 
metadata:
  name: init-pod 
spec:
  initContainers:
    - name: init-con 
      image: busybox
      command: ["sh", "-c", "sleep 10"]
  containers:
    - name: app-con 
      image: nginx
      ports:
        - containerPort: 80
    - name: sidecar
      image: busybox
      command: ["sh","-c","sleep 100"]
      