apiVersion: v1
kind: Pod
metadata:
  name: my-new-pd
spec:
  containers:
    - name: new-c
      image: registry.k8s.io/busybox
      command: ["sh", "-c", "touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600"]
      livenessProbe:
        exec:
          command: ["sh", "-c", "cat /tmp/healthy"]
        initialDelaySeconds: 5
        periodSeconds: 5
