apiVersion: v1
kind: Persistantvolume
metadata:
 name: my-pv
spec:
 storageClassName: local
 accessModes:
  - ReadWriteMany
 capacity:
   storage: 2GI
 hostPath:
  path: "/home/ubuntu/my-vol"

--------------

apiVersion: v1
kind: PersistantVolumeClaim
metadata:
 name: my-pvc
spec:
 storageClassName: local
 accessModes:
  - ReadWriteMany
 resources:
   request:
    storage: 1Gi

------------------

apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deploy-pv
spec:
 replicas: 4
 selectors:
  matchLabels:
   app: PV
 templae:
  spce:
   containers:
    name: mu-pod
    image: nginx
    ports:
     - containerPort: 80
    volumes:
     - name: my-volume-pv
       mountPath: "apps/v"
   volumes: 
    - name: my-volume-pv
      PersistantVolumeClaim:
       - name: my-pvc
  metadata:
   lables:
    app: PV  