apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-ac

---

apiVersion: v1
kind: Secret
metadata:
  name: helm-token
  annotations:
    kubernetes.io/service-account.name: helm-ac
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces", "nodes"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-bind
subjects:
  - kind: ServiceAccount
    name: helm-ac
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-role
