apiVersion: rbac.authorization.k8s.io
kind: Role
metatda:
 name: pod-reader
 namespace: defalut
rules:
-apiGroups: [""]
 resources: ["Pods, services"]
 verbs: ["get", "watch","list"]

---------------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
 name: SA_ROLE
subjects:
 - type: ServiceAccount 
   name: SA-Account 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  type: Role
  name: SA_ROLE
