apiVersion: v1
kind: Secret
metadata: 
 name: my-secret
type: Opaque
data:
 env: aGFYC2H1cG==

---------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
 name: my-config
data:
 env: Rakshu

---------------------------------------

apiVersion: v1
kind: Pod
metadata:
 name: my-pod
spec:
 containers:
  - name: my-pod
    image: nginx
    ports:
     - containerPort: 80
    volumeMounts:
     - name: secret-vol
       mountpath: /app/secret
     - name: config-mao
       mountpath: /app/config
 volumes:
  - name: secret-vol
    secret:
     secretName: new-secret
  - name: config-map
    congigMap:
     name: my-con
 
 