apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  db-password: "base64encodedvalue"

---

apiVersion: v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  template:
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 8080
        env:
        - name: pass
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db-password