apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: set-s
spec:
  replicas: 4
  serviceName: "nginx-service"
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: set-pod
        image: nginx
        ports:
        - containerPort: 80
