apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: my-st
provisioner: kubernetes.io/aws-ebs
parameters:
 type: gp2
 iopsPerGB: "10"
 fsType: ext2
reclaimPolicy: Retain
allowVolumeExpansion: true